version: '2'
services:
 flink-master:
   image: ruizhizhong058/flink-master:1.18.1-hadoop3.3
   hostname: flink-master
   container_name: flink-master
#   networks:
#     - hadoop
   ports:
     - "8080:8080"
     - "8081:8081"

 flink-worker:
   image: ruizhizhong058/flink-worker:1.18.1-hadoop3.3
   hostname: flink-worker
   container_name: flink-worker
#   networks:
#     - hadoop
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
#     - FLINK_NUM_TASK_SLOTS=2
   depends_on:
      - flink-master

#networks:
#  default:
#    external:
#      name: hadoop
